{
    "name": "Field Visit",
    "version": "17.0.1.0.0",
    "development_status": "Beta",
    "category": "Field Visit",
    "author": "Mukesh",
    "license": "AGPL-3",
    "depends": ['hr',"calendar", "base", "web","customer_visibility"],
    "data": [
        "security/field_visit_security.xml",
        "security/ir.model.access.csv",
        'security/field_visit_timesheet_rules.xml',
        "data/field_visit_sequence.xml",
        "wizards/field_visit_close_wiz_view.xml",
        "wizards/field_visit_template_create.xml",
        "wizards/field_visit_justify_wizard.xml",
        "views/field_visit_views.xml",
        "views/route.xml",
        "views/route_assignment_views.xml",
        "views/field_visit_close_reason_views.xml",
        "views/field_visit_template_views.xml",
        "views/field_visit_menu.xml",
        "views/res_partner.xml",
        "views/res_company_views.xml",
        # "views/crm_lead.xml",
        "data/ir_cron_data.xml",
        "views/visit_timer_tracking.xml",
        "views/res_config_settings_views.xml",
        "views/visit_objective_tags_views.xml",
        # "views/state_city_views.xml",
        "views/city_zip_views.xml",
    ],
    'assets': {
        'web.assets_backend': [
            'field_visit/static/src/js/field_visit_calendar_renderer.js',
            # 'field_visit/static/src/js/enter_navigation.js',
            # 'field_visit/static/src/js/multi_selection_widget.js',
            # 'field_visit/static/src/xml/multi_selection_widget.xml',
            'field_visit/static/src/views/field_dashboard.js',
            'field_visit/static/src/views/field_dashboard.xml',
            'field_visit/static/src/views/field_listview.js',
            'field_visit/static/src/views/field_listview.xml',
            # 'field_visit/static/src/css/text.css',
        ],

    },
    'images': ['static/description/icon.png'],
    "installable": True,

}
